name: flutter_twilio_conversations_example
description: Demonstrates how to use the flutter_twilio_conversations plugin.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  redux: ^5.0.0
  flutter_redux: ^0.8.2
  redux_epics: ^0.15.0
  equatable: ^2.0.3
  flutter_local_notifications:
  fluttertoast: ^8.0.8
  cached_network_image: ^3.2.0
  permission_handler: ^8.3.0
  device_info_plus:
  image_picker: ^0.8.4+4

  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  flutter_lints: ^1.0.4
  flutter_twilio_conversations:
    path: ../

flutter:
  uses-material-design: true

